테마 색상 변경 + 유지,보수를 위해 Color.kt, Theme파일 수정
f-lab-edu/sunflower_jsh pull request #20
Opened 2023-04-28 10:13 UTC by shjung53

## 변경사항
- 테마 색상 변경
  - 기존 테마 색상의 배합이 어색해서 변경
- Color.kt, Theme 파일 수정 
  - 추후 테마 색상 변경 시에 용이하도록 변경
  - theme builder로 추출 시의 파일 형태로 유지

 ## before & after
<p align="center">
    <img src ="https://user-images.githubusercontent.com/90888718/235120735-66aca213-fe25-4834-beed-f9946d5de9b1.png" align="center" width="40%">
    <img src ="(https://user-images.githubusercontent.com/90888718/235120745-ce43ac0a-73d3-4679-a8de-78f24c8a7f87.png" align="center" width="40%">
</p>

2023-04-28 12:48 UTC, jerry-f-lab submitted a review, later dismissed
lgtm

2023-04-28 12:50 UTC, jerry-f-lab commented on app/src/main/java/com/example/sunflower/theme/Color.kt
> +val md_theme_light_primary = Color(0xFF426915)
kotlin 네이밍 규칙 위반입니다.
https://kotlinlang.org/docs/coding-conventions.html#property-names

ktlint가 왜 지적을 안해주었을까요?

2023-04-28 12:50 UTC, jerry-f-lab requested changes

2023-04-28 12:50 UTC, jerry-f-lab commented on app/src/main/java/com/example/sunflower/theme/Color.kt
> +val md_theme_light_primary = Color(0xFF426915)
kotlin 네이밍 규칙 위반입니다.
https://kotlinlang.org/docs/coding-conventions.html#property-names

ktlint가 왜 지적을 안해주었을까요?

2023-04-29 06:33 UTC, shjung53 commented on app/src/main/java/com/example/sunflower/theme/Color.kt
> +val md_theme_light_primary = Color(0xFF426915)
experimental rule에서 property 네이밍 강제하는 기능이 있어서 추가했습니다.

2023-04-29 11:02 UTC, jerry-f-lab approved these changes
lgtm

2023-04-29 11:02 UTC, merged